# Generated by Django 2.1.4 on 2019-02-09 17:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190209_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
